---
title: PowerShell Script - test.ps1
---
graph TD
    write-hello --> write-goodbye
    not-called
    main --> write-hello
    main --> write-goodbye
    included --> write-hello
    write-goodbye
